recursive first try

diff --git a/recycle b/recycle
--- a/recycle
+++ b/recycle
@@ -18,11 +18,13 @@ fi
 function optFunc(){
     interactive=False
     verbose=False
-    while getopts :iv opt
+    recursive=False
+    while getopts :ivr opt
     do
         case $opt in
             i) interactive=True;;
             v) verbose=True;;
+            r) recursive=True;;
             *) echo bad option - $OPTARG
                 echo Try 'recycle --help for more information.'
                 exit 1;;
@@ -31,20 +33,25 @@ function optFunc(){
     done
 }
 
+function recyclingFiles(){
+    inode=$(ls -i $PWD/$1| cut -d" " -f1)
+    name=$1\_$inode
+    mv $PWD/$1 $HOME/recyclebin/$name
+    echo "$name:$PWD/$1" >> $HOME/.restore.info
+
+}
+
 
 function recycleFunc(){
     
     response="Y"  
 
-    if $interactive
-    then
-        read -p "Do you want to recycle the file? " response  
-    fi
 
     if [[ $# -eq 0 ]]
     then
         echo "error1:no filename provided"
         exit 1
+
     else
         for fileName in $*
         do
@@ -52,32 +59,50 @@ function recycleFunc(){
             then
                 echo "error2: File does not exist"
                 exit 2
-            elif [[ -d $fileName ]]
-            then    
-                echo "error3: Directory name provided"
-                exit 3
+
             elif [[ $fileName == "recycle" ]]
             then    
                 echo "error4: Attempting to delete recycle - operation aborted"
-                exit 4  
+                exit 3 
+
+            elif [[ -d $fileName ]]
+            then
+
+                if $recursive
+                then
+                    
+                    fullpaths=$(find $PWD/$fileName -type f)
+                    for fullpath in $fullpaths:
+                    do
+                        inode=$(ls -i $fullpath | cut -d" " -f1)
+                        fn=$(find $fullpath -type f| egrep -o "[/][^/]*$"|cut -d/ -f2)
+                        name=$fn\_$inode
+                        mv $fullpath $HOME/recyclebin/$name
+                        echo "$name:$fullpath" >> $HOME/.restore.info
+                    done
+                else
+                    echo "error3: Directory name provided"
+                    exit 4 
+                fi
+
+
             else 
                 if $interactive
                 then
-                read -p "Do you want to recycle the file? " userResponse
+                read -p "Do you want to recycle $fileName ? " userResponse
                 response=$userResponse  
                 fi 
 
                 if [[ $response =~ ^[yY] ]]
                 then
                 
-                    inode=$(ls -i $PWD/$fileName| cut -d" " -f1)
-                    name=$fileName\_$inode
-                    mv $PWD/$fileName $HOME/recyclebin/$name
-                    echo "$name:$PWD/$fileName" >> $HOME/.restore.info
+                    recyclingFiles $fileName
+                    
                     if $verbose
                     then
                         echo "$fileName under the $PWD is deleted. The file reference number $name"
                     fi
+
                 else
                     echo "do not recycle the file"
                fi
@@ -92,31 +117,3 @@ optFunc $*
 shift $[OPTIND-1]
 recycleFunc $*
 
-
-
-# fileName=$1
-
-
-# if [[ $# -eq 0 ]]
-# then
-#     echo "error1: No filename provided"
-#     exit 1
-# elif [[ ! -f $fileName ]]
-# then 
-#     echo "error2: File does not exist"
-#     exit 2
-# elif [[ -d $fileName ]]
-# then    
-#     echo "error3: Directory name provided"
-#     exit 3
-# elif [[ $fileName == "recycle" ]]
-# then    
-#     echo "error4: Attempting to delete recycle - operation aborted"
-#     exit 4
-# else
-#     inode=$(ls -i $PWD/$fileName| cut -d" " -f1)
-#     name=$fileName\_$inode
-#     mv $PWD/$fileName $HOME/recyclebin/$name
-#     echo "$name:$PWD/$fileName" >> $HOME/.restore.info 
-
-# fi
