before testing: restore file recycled recursively

diff --git a/recycle b/recycle
--- a/recycle
+++ b/recycle
@@ -62,49 +62,65 @@ function recycleFunc(){
 
             elif [[ $fileName == "recycle" ]]
             then    
-                echo "error4: Attempting to delete recycle - operation aborted"
+                echo "error3: Attempting to delete recycle - operation aborted"
                 exit 3 
 
             elif [[ -d $fileName ]]
             then
-
                 if $recursive
                 then
+                    
                     fullpaths=$(find $PWD/$fileName -type f)
-                    for fullpath in $fullpaths
+                    for fullpath in $fullpaths:
                     do
 
-                        if $interactive
-                        then
-                        read -p "Do you want to recycle $fileName ? " userResponse
-                        response=$userResponse 
-                        fi
-                        if [[ $response =~ ^[yY] ]]
-                        then
-                            inode=$(ls -i $fullpath | cut -d" " -f1)
-                            fn=$(find $fullpath -type f| egrep -o "[/][^/]*$"|cut -d/ -f2)
-                            name=$fn\_$inode
-                            mv $fullpath $HOME/recyclebin/$name
-                            echo "$name:$fullpath" >> $HOME/.restore.info
+                        inode=$(ls -i $fullpath | cut -d" " -f1)
+                        fn=$(find $fullpath -type f| egrep -o "[/][^/]*$"|cut -d/ -f2)
+                        name=$fn\_$inode
+                        mv $fullpath $HOME/recyclebin/$name
+                        echo "$name:$fullpath" >> $HOME/.restore.info
 
-                            if $verbose
-                            then
-                                echo "$fileName under the $PWD is deleted. The file reference number $name"
-                            fi
-                        else 
-                            echo "do not recycle the file"
-                        fi
- 
                     done
                     $(rm -r $PWD/$fileName)
-
                 else
-                    echo "error3: Directory name provided"
+                    echo "error4: Directory name provided"
                     exit 4 
                 fi
+                
 
+                # if $recursive
+                # then
+                #     fullpaths=$(find $PWD/$fileName -type f)
+                #     for fullpath in $fullpaths
+                #     do
 
-            else 
+                #         if $interactive
+                #         then
+                #         read -p "Do you want to recycle $fileName ? " userResponse
+                #         response=$userResponse 
+                #         fi
+                #         if [[ $response =~ ^[yY] ]]
+                #         then
+                #             inode=$(ls -i $fullpath | cut -d" " -f1)
+                #             fn=$(find $fullpath -type f| egrep -o "[/][^/]*$"|cut -d/ -f2)
+                #             name=$fn\_$inode
+                #             mv $fullpath $HOME/recyclebin/$name
+                #             echo "$name:$fullpath" >> $HOME/.restore.info
+
+                #             if $verbose
+                #             then
+                #                 echo "$fileName under the $PWD is deleted. The file reference number $name"
+                #             fi
+                #         else 
+                #             echo "do not recycle the file"
+                #         fi
+                    # done
+                # else
+                #     echo "error3: Directory name provided"
+                #     exit 4 
+                # fi
+            elif [[ -f $fileName ]]
+            then
                 if $interactive
                 then
                 read -p "Do you want to recycle $fileName ? " userResponse
@@ -124,6 +140,9 @@ function recycleFunc(){
                 else
                     echo "do not recycle the file"
                fi
+
+            else 
+                echo " file type is not recognised"
             fi
         done
     fi
